const d = [
    {
        id: 1,
        user_id: 5,
        title: "ex",
        description:
            "Rerum sequi nam voluptatem quia. Placeat et dolorem dolor soluta vero. Voluptas nam quidem qui esse occaecati nam. Maiores sit assumenda vel repellat.",
        area_id: 4,
        nature_id: 2,
        profession_id: 1,
        experience_months: null,
        salary: 23744,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 2,
        user_id: 7,
        title: "sint",
        description:
            "Consequatur autem ut qui corrupti tempora nostrum deleniti. Libero reiciendis tempore velit omnis. Id aut eos ut.",
        area_id: 2,
        nature_id: 1,
        profession_id: 5,
        experience_months: null,
        salary: 1700,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 3,
        user_id: 10,
        title: "et",
        description:
            "Aut assumenda qui iusto sunt atque. Dolorem consequatur ut repudiandae animi facere consectetur autem. Autem voluptatem quia dolorum rerum inventore sint.",
        area_id: 5,
        nature_id: 3,
        profession_id: 3,
        experience_months: null,
        salary: 17469,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 4,
        user_id: 6,
        title: "dolores",
        description:
            "Non eum laudantium eum modi autem nisi. Dolor quidem sit possimus iusto possimus odio similique. Provident molestiae non fuga doloribus amet eum cum quo. Provident et ut vel ut dolorem.",
        area_id: 4,
        nature_id: 2,
        profession_id: 2,
        experience_months: null,
        salary: 25464,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 5,
        user_id: 3,
        title: "id",
        description:
            "Est molestias et blanditiis labore quia. Quia et eligendi ipsa et quod. Aut quibusdam incidunt voluptatem. Ab dicta corporis eum dicta distinctio velit. Incidunt voluptatem vel unde voluptatem accusantium beatae.",
        area_id: 4,
        nature_id: 3,
        profession_id: 6,
        experience_months: null,
        salary: 43785,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 6,
        user_id: 7,
        title: "itaque",
        description:
            "Consequuntur quas repudiandae adipisci excepturi doloremque eos. Corporis sit quas sunt voluptate cum quas. Voluptatum quo et tempora. Voluptatem molestiae facere sunt quia placeat enim provident. Cupiditate quis id sed molestiae facere quisquam.",
        area_id: 1,
        nature_id: 3,
        profession_id: 1,
        experience_months: null,
        salary: 49281,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 7,
        user_id: 5,
        title: "suscipit",
        description:
            "Quia sed rerum aut est aut blanditiis omnis. Iusto accusamus voluptatum ex in possimus vitae velit. Dolores aut quidem magnam veritatis consequatur. Et saepe reprehenderit assumenda velit.",
        area_id: 3,
        nature_id: 3,
        profession_id: 2,
        experience_months: null,
        salary: 2440,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 8,
        user_id: 1,
        title: "unde",
        description:
            "Corporis aliquid qui impedit inventore repellendus fugit. Natus neque magnam aut et ratione quos corporis. Qui quaerat molestias aut asperiores qui rerum. Dolorem consequuntur accusantium sint quia id.",
        area_id: 6,
        nature_id: 1,
        profession_id: 5,
        experience_months: null,
        salary: 29795,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 9,
        user_id: 3,
        title: "quam",
        description:
            "Ullam minus architecto ut. Fuga mollitia non eum cum facere voluptatibus earum. Laudantium non ipsa est corporis.",
        area_id: 2,
        nature_id: 3,
        profession_id: 7,
        experience_months: null,
        salary: 43459,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 10,
        user_id: 3,
        title: "odio",
        description:
            "Magnam est ut distinctio nihil et nemo consequatur. Qui officia in ut illum facere magni. Sed rerum quo dolor voluptas voluptatem ut amet. Aliquam autem cupiditate autem illum quas.",
        area_id: 5,
        nature_id: 2,
        profession_id: 6,
        experience_months: null,
        salary: 16454,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 11,
        user_id: 3,
        title: "aut",
        description:
            "Blanditiis odio totam voluptas eum reiciendis sit repudiandae laborum. Occaecati illo saepe itaque cupiditate nemo est id. Explicabo et dolores minus ut placeat aut.",
        area_id: 2,
        nature_id: 1,
        profession_id: 5,
        experience_months: null,
        salary: 9487,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 12,
        user_id: 10,
        title: "unde",
        description:
            "Aspernatur quae molestiae molestiae adipisci dignissimos iusto. Ipsum magni qui quod sed rerum corporis. Suscipit excepturi ipsam enim culpa molestias. Accusantium ea tempore iste illo magnam deleniti voluptatem quam. Mollitia molestiae sapiente ab quia saepe vel vitae.",
        area_id: 3,
        nature_id: 2,
        profession_id: 5,
        experience_months: null,
        salary: 4278,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 13,
        user_id: 5,
        title: "corporis",
        description:
            "Tempora magni sunt quae itaque. Voluptate provident expedita ipsum ea. Harum voluptatem quam delectus aut consequuntur et. Consequatur facilis rerum perferendis qui ut sed ipsum.",
        area_id: 2,
        nature_id: 2,
        profession_id: 7,
        experience_months: null,
        salary: 30782,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 14,
        user_id: 7,
        title: "porro",
        description:
            "Voluptatem corporis quia suscipit aut occaecati libero. Distinctio omnis eos rem aut in. Aut consequatur et est optio illo.",
        area_id: 4,
        nature_id: 2,
        profession_id: 6,
        experience_months: null,
        salary: 28902,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 15,
        user_id: 4,
        title: "alias",
        description:
            "Rem quam aliquid temporibus dolores odit aperiam. Recusandae rerum temporibus numquam nemo eos. Placeat eum autem sunt vel.",
        area_id: 1,
        nature_id: 1,
        profession_id: 2,
        experience_months: null,
        salary: 39751,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 16,
        user_id: 5,
        title: "eligendi",
        description:
            "Ea quia vel velit ipsa aut ipsam voluptas ipsam. Rerum voluptas dolores mollitia qui non dignissimos dolor totam. Ad temporibus eos explicabo consequatur.",
        area_id: 3,
        nature_id: 3,
        profession_id: 5,
        experience_months: null,
        salary: 17783,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 17,
        user_id: 11,
        title: "quae",
        description:
            "Quasi quidem et unde molestias. Ut ut ea sed aspernatur. Et sed quasi et excepturi dicta fuga. Quia ut est dolor esse possimus repudiandae enim illo.",
        area_id: 4,
        nature_id: 3,
        profession_id: 3,
        experience_months: null,
        salary: 3789,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 18,
        user_id: 6,
        title: "delectus",
        description:
            "Fugit accusamus dolor voluptate exercitationem saepe repellendus. Fugiat et molestias cum dolor. Repudiandae corrupti adipisci velit minima voluptas.",
        area_id: 1,
        nature_id: 3,
        profession_id: 6,
        experience_months: null,
        salary: 16978,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 19,
        user_id: 8,
        title: "nemo",
        description:
            "Sed est sequi itaque magni et doloremque. Optio animi ut debitis magnam incidunt. Et non consequatur quod est optio deleniti minima.",
        area_id: 4,
        nature_id: 1,
        profession_id: 2,
        experience_months: null,
        salary: 2800,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 20,
        user_id: 6,
        title: "quod",
        description:
            "Similique hic quo amet vel molestiae. Officiis rerum voluptas fugiat atque. Nisi veniam sunt dolorum doloremque sunt qui sunt culpa. Nulla sed vitae distinctio ullam nemo fugiat.",
        area_id: 5,
        nature_id: 3,
        profession_id: 7,
        experience_months: null,
        salary: 33493,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 21,
        user_id: 12,
        title: "test",
        description: "ererrewrewrwerwerwerwer",
        area_id: 7,
        nature_id: 2,
        profession_id: 1,
        experience_months: 32,
        salary: 1000,
        created_at: "2024-02-07T20:26:39.000000Z",
        updated_at: "2024-02-07T20:26:39.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 22,
        user_id: 12,
        title: "test",
        description: "ererrewrewrwerwerwerwer",
        area_id: 9,
        nature_id: 2,
        profession_id: 1,
        experience_months: 32,
        salary: 1000,
        created_at: "2024-02-07T20:26:39.000000Z",
        updated_at: "2024-02-07T20:26:39.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 23,
        user_id: 12,
        title: "test",
        description: "ererrewrewrwerwerwerwer",
        area_id: 8,
        nature_id: 2,
        profession_id: 1,
        experience_months: 32,
        salary: 1000,
        created_at: "2024-02-07T20:26:39.000000Z",
        updated_at: "2024-02-07T20:26:39.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 24,
        user_id: 12,
        title: "test",
        description: "ererrewrewrwerwerwerwer",
        area_id: 10,
        nature_id: 2,
        profession_id: 1,
        experience_months: 32,
        salary: 1000,
        created_at: "2024-02-07T20:26:39.000000Z",
        updated_at: "2024-02-07T20:26:39.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 25,
        user_id: 12,
        title: "new test",
        description: "sadasdas",
        area_id: 1,
        nature_id: 1,
        profession_id: 2,
        experience_months: 0,
        salary: 1234,
        created_at: "2024-02-09T14:03:53.000000Z",
        updated_at: "2024-02-09T14:03:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 26,
        user_id: 12,
        title: "test find",
        description: "43e \u0437",
        area_id: 1,
        nature_id: 1,
        profession_id: 3,
        experience_months: 36,
        salary: 1234,
        created_at: "2024-02-11T17:52:27.000000Z",
        updated_at: "2024-02-11T17:52:27.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
];
const asd = [
    {
        id: 1,
        user_id: 5,
        title: "ex",
        description:
            "Rerum sequi nam voluptatem quia. Placeat et dolorem dolor soluta vero. Voluptas nam quidem qui esse occaecati nam. Maiores sit assumenda vel repellat.",
        area_id: 4,
        nature_id: 2,
        profession_id: 1,
        experience_months: null,
        salary: 23744,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 2,
        user_id: 7,
        title: "sint",
        description:
            "Consequatur autem ut qui corrupti tempora nostrum deleniti. Libero reiciendis tempore velit omnis. Id aut eos ut.",
        area_id: 2,
        nature_id: 1,
        profession_id: 5,
        experience_months: null,
        salary: 1700,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 3,
        user_id: 10,
        title: "et",
        description:
            "Aut assumenda qui iusto sunt atque. Dolorem consequatur ut repudiandae animi facere consectetur autem. Autem voluptatem quia dolorum rerum inventore sint.",
        area_id: 5,
        nature_id: 3,
        profession_id: 3,
        experience_months: null,
        salary: 17469,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 4,
        user_id: 6,
        title: "dolores",
        description:
            "Non eum laudantium eum modi autem nisi. Dolor quidem sit possimus iusto possimus odio similique. Provident molestiae non fuga doloribus amet eum cum quo. Provident et ut vel ut dolorem.",
        area_id: 4,
        nature_id: 2,
        profession_id: 2,
        experience_months: null,
        salary: 25464,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 5,
        user_id: 3,
        title: "id",
        description:
            "Est molestias et blanditiis labore quia. Quia et eligendi ipsa et quod. Aut quibusdam incidunt voluptatem. Ab dicta corporis eum dicta distinctio velit. Incidunt voluptatem vel unde voluptatem accusantium beatae.",
        area_id: 4,
        nature_id: 3,
        profession_id: 6,
        experience_months: null,
        salary: 43785,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 6,
        user_id: 7,
        title: "itaque",
        description:
            "Consequuntur quas repudiandae adipisci excepturi doloremque eos. Corporis sit quas sunt voluptate cum quas. Voluptatum quo et tempora. Voluptatem molestiae facere sunt quia placeat enim provident. Cupiditate quis id sed molestiae facere quisquam.",
        area_id: 1,
        nature_id: 3,
        profession_id: 1,
        experience_months: null,
        salary: 49281,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 7,
        user_id: 5,
        title: "suscipit",
        description:
            "Quia sed rerum aut est aut blanditiis omnis. Iusto accusamus voluptatum ex in possimus vitae velit. Dolores aut quidem magnam veritatis consequatur. Et saepe reprehenderit assumenda velit.",
        area_id: 3,
        nature_id: 3,
        profession_id: 2,
        experience_months: null,
        salary: 2440,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 8,
        user_id: 1,
        title: "unde",
        description:
            "Corporis aliquid qui impedit inventore repellendus fugit. Natus neque magnam aut et ratione quos corporis. Qui quaerat molestias aut asperiores qui rerum. Dolorem consequuntur accusantium sint quia id.",
        area_id: 6,
        nature_id: 1,
        profession_id: 5,
        experience_months: null,
        salary: 29795,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 9,
        user_id: 3,
        title: "quam",
        description:
            "Ullam minus architecto ut. Fuga mollitia non eum cum facere voluptatibus earum. Laudantium non ipsa est corporis.",
        area_id: 2,
        nature_id: 3,
        profession_id: 7,
        experience_months: null,
        salary: 43459,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 10,
        user_id: 3,
        title: "odio",
        description:
            "Magnam est ut distinctio nihil et nemo consequatur. Qui officia in ut illum facere magni. Sed rerum quo dolor voluptas voluptatem ut amet. Aliquam autem cupiditate autem illum quas.",
        area_id: 5,
        nature_id: 2,
        profession_id: 6,
        experience_months: null,
        salary: 16454,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 11,
        user_id: 3,
        title: "aut",
        description:
            "Blanditiis odio totam voluptas eum reiciendis sit repudiandae laborum. Occaecati illo saepe itaque cupiditate nemo est id. Explicabo et dolores minus ut placeat aut.",
        area_id: 2,
        nature_id: 1,
        profession_id: 5,
        experience_months: null,
        salary: 9487,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 12,
        user_id: 10,
        title: "unde",
        description:
            "Aspernatur quae molestiae molestiae adipisci dignissimos iusto. Ipsum magni qui quod sed rerum corporis. Suscipit excepturi ipsam enim culpa molestias. Accusantium ea tempore iste illo magnam deleniti voluptatem quam. Mollitia molestiae sapiente ab quia saepe vel vitae.",
        area_id: 3,
        nature_id: 2,
        profession_id: 5,
        experience_months: null,
        salary: 4278,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 13,
        user_id: 5,
        title: "corporis",
        description:
            "Tempora magni sunt quae itaque. Voluptate provident expedita ipsum ea. Harum voluptatem quam delectus aut consequuntur et. Consequatur facilis rerum perferendis qui ut sed ipsum.",
        area_id: 2,
        nature_id: 2,
        profession_id: 7,
        experience_months: null,
        salary: 30782,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 14,
        user_id: 7,
        title: "porro",
        description:
            "Voluptatem corporis quia suscipit aut occaecati libero. Distinctio omnis eos rem aut in. Aut consequatur et est optio illo.",
        area_id: 4,
        nature_id: 2,
        profession_id: 6,
        experience_months: null,
        salary: 28902,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 15,
        user_id: 4,
        title: "alias",
        description:
            "Rem quam aliquid temporibus dolores odit aperiam. Recusandae rerum temporibus numquam nemo eos. Placeat eum autem sunt vel.",
        area_id: 1,
        nature_id: 1,
        profession_id: 2,
        experience_months: null,
        salary: 39751,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 16,
        user_id: 5,
        title: "eligendi",
        description:
            "Ea quia vel velit ipsa aut ipsam voluptas ipsam. Rerum voluptas dolores mollitia qui non dignissimos dolor totam. Ad temporibus eos explicabo consequatur.",
        area_id: 3,
        nature_id: 3,
        profession_id: 5,
        experience_months: null,
        salary: 17783,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 17,
        user_id: 11,
        title: "quae",
        description:
            "Quasi quidem et unde molestias. Ut ut ea sed aspernatur. Et sed quasi et excepturi dicta fuga. Quia ut est dolor esse possimus repudiandae enim illo.",
        area_id: 4,
        nature_id: 3,
        profession_id: 3,
        experience_months: null,
        salary: 3789,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 18,
        user_id: 6,
        title: "delectus",
        description:
            "Fugit accusamus dolor voluptate exercitationem saepe repellendus. Fugiat et molestias cum dolor. Repudiandae corrupti adipisci velit minima voluptas.",
        area_id: 1,
        nature_id: 3,
        profession_id: 6,
        experience_months: null,
        salary: 16978,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 19,
        user_id: 8,
        title: "nemo",
        description:
            "Sed est sequi itaque magni et doloremque. Optio animi ut debitis magnam incidunt. Et non consequatur quod est optio deleniti minima.",
        area_id: 4,
        nature_id: 1,
        profession_id: 2,
        experience_months: null,
        salary: 2800,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 20,
        user_id: 6,
        title: "quod",
        description:
            "Similique hic quo amet vel molestiae. Officiis rerum voluptas fugiat atque. Nisi veniam sunt dolorum doloremque sunt qui sunt culpa. Nulla sed vitae distinctio ullam nemo fugiat.",
        area_id: 5,
        nature_id: 3,
        profession_id: 7,
        experience_months: null,
        salary: 33493,
        created_at: "2024-02-03T21:00:53.000000Z",
        updated_at: "2024-02-03T21:00:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 21,
        user_id: 12,
        title: "test",
        description: "ererrewrewrwerwerwerwer",
        area_id: 7,
        nature_id: 2,
        profession_id: 1,
        experience_months: 32,
        salary: 1000,
        created_at: "2024-02-07T20:26:39.000000Z",
        updated_at: "2024-02-07T20:26:39.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 22,
        user_id: 12,
        title: "test",
        description: "ererrewrewrwerwerwerwer",
        area_id: 9,
        nature_id: 2,
        profession_id: 1,
        experience_months: 32,
        salary: 1000,
        created_at: "2024-02-07T20:26:39.000000Z",
        updated_at: "2024-02-07T20:26:39.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 23,
        user_id: 12,
        title: "test",
        description: "ererrewrewrwerwerwerwer",
        area_id: 8,
        nature_id: 2,
        profession_id: 1,
        experience_months: 32,
        salary: 1000,
        created_at: "2024-02-07T20:26:39.000000Z",
        updated_at: "2024-02-07T20:26:39.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 24,
        user_id: 12,
        title: "test",
        description: "ererrewrewrwerwerwerwer",
        area_id: 10,
        nature_id: 2,
        profession_id: 1,
        experience_months: 32,
        salary: 1000,
        created_at: "2024-02-07T20:26:39.000000Z",
        updated_at: "2024-02-07T20:26:39.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 25,
        user_id: 12,
        title: "new test",
        description: "sadasdas",
        area_id: 1,
        nature_id: 1,
        profession_id: 2,
        experience_months: 0,
        salary: 1234,
        created_at: "2024-02-09T14:03:53.000000Z",
        updated_at: "2024-02-09T14:03:53.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
    {
        id: 26,
        user_id: 12,
        title: "test find",
        description: "- \u041a\u043e\u0436\u0435\u043d \u0437 ",
        area_id: 1,
        nature_id: 1,
        profession_id: 3,
        experience_months: 36,
        salary: 1234,
        created_at: "2024-02-11T17:52:27.000000Z",
        updated_at: "2024-02-11T17:52:27.000000Z",
        deleted_at: null,
        received_reviews: [],
    },
];
